fos_rest:
    param_fetcher_listener: true
    routing_loader:
      default_format: json
    view:
        mime_types:
            json: ['application/json', 'application/json;version=1.0', 'application/json;version=1.1', 'application/json;version=1.2']
        view_response_listener: 'force'
        #formats:
        #    xml: true
        #    json: true
        templating_formats:
            html: true
        force_redirects:
            html: true
        #failed_validation: HTTP_BAD_REQUEST
        #default_engine: twig

    format_listener:
        rules:
            - { path: ^/, priorities: [ html, json, xml ], fallback_format: ~, prefer_extension: true }

    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true

    allowed_methods_listener: true
    access_denied_listener:
        json: true
    body_listener: true
