sonata_admin:
    templates:
      layout: AppBundle::standard_layout.html.twig
    options:
        use_select2:   true # disable select2
    templates:
        dashboard: SonataAdminBundle:Core:dashboard.html.twig
    title:
        A Dog To Me
