services:
  blocks.manager:
    class: AppBundle\Model\BlocksManager
    arguments:
      - AppBundle:Blocks
    calls:
      - [setContainer, ["@service_container"]]

  records.manager:
    class: AppBundle\Model\RecordsManager
    arguments:
      - AppBundle:Records
    calls:
      - [setContainer, ["@service_container"]]

  users.manager:
        class: AppBundle\Model\UsersManager
        arguments:
          - AppBundle:User
        calls:
          - [setContainer, ["@service_container"]]

  friends.manager:
      class: AppBundle\Model\FriendsManager
      arguments:
        - AppBundle:Friends
      calls:
        - [setContainer, ["@service_container"]]
