services:
  blocks.manager:
    class: AppBundle\Model\BlocksManager
    arguments:
      - AppBundle:Blocks
    calls:
      - [setContainer, ["@service_container"]]
      - [securityContext, ["@security.token_storage"]]
      - [setBlocksUsers, ["@blocks_users.manager"]]

  blocks_users.manager:
      class: AppBundle\Model\BlocksUsersManager
      arguments:
        - AppBundle:BlocksUsers
      calls:
        - [setContainer, ["@service_container"]]

  records.manager:
    class: AppBundle\Model\RecordsManager
    arguments:
      - AppBundle:Records
    calls:
      - [setContainer, ["@service_container"]]

  users.manager:
        class: AppBundle\Model\UsersManager
        arguments:
          - AppBundle:User
        calls:
          - [setContainer, ["@service_container"]]

  friends.manager:
      class: AppBundle\Model\FriendsManager
      arguments:
        - AppBundle:Friends
      calls:
        - [setContainer, ["@service_container"]]

  categories.manager:
        class: AppBundle\Model\CategoriesManager
        arguments:
          - AppBundle:Categories
        calls:
          - [setContainer, ["@service_container"]]
