services:
    # ...
    admin.blocks:
        class: AppBundle\Admin\BlocksAdmin
        arguments: [~, AppBundle\Entity\Blocks, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Blocks }