services:
    blocks.type:
        class: AppBundle\Form\BlocksType
        tags:
            - { name: form.type, alias: blocks }

    blocks_categories.type:
        class: AppBundle\Form\BlocksCategoriesType
        tags:
            - { name: form.type, alias: blocks_categories }

    categories_concepts.type:
            class: AppBundle\Form\CategoriesConceptsType
            tags:
                - { name: form.type, alias: categories_concepts }

    blocks_users.type:
        class: AppBundle\Form\BlockUsersType
        tags:
            - { name: form.type, alias: block_users }

    records.type:
        class: AppBundle\Form\RecordsType
        tags:
            - { name: form.type, alias: records }
